VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsApplicationEvents"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'ExcelSteps_clsApplicationEvents_cls.vb
'Version 12/16/25
'Application Events
Option Explicit
Public WithEvents AppEvent As Application
Attribute AppEvent.VB_VarHelpID = -1
